# Generated by Django 6.0.2 on 2026-03-03 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='image_name',
            field=models.CharField(default='no_hero.png', max_length=100),
        ),
        migrations.AlterField(
            model_name='hero',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
